Algoritmo "Operador E"                                                                                                                                                                                "

Var
azul, vermelho: inteiro


Inicio

escreva ("Informe o valor de AZUL:")
leia (azul)
escreva ("Informe o valor de VERMELHO:")
leia (vermelho)

se (azul =15) E (vermelho =10) entao
 escreva ("Acesso permitido")
senao
 escreva ("Tentativa de acesso negada")
fimse


Fimalgoritmo